---
- name: DAT | ASSETS - PUSH | clean assets from the controller (pre-work)
  include_tasks: assets_clean.yml

- name: DAT | ASSETS - PUSH | pull assets from local to controller
  synchronize:
    src: "{{ item.local }}"
    dest: "{{ dat_assets_controller_temp_dir }}/{{ idx }}"
    mode: pull
    archive: no
    delete: yes
    recursive: yes
  with_items: "{{ dat_assets_dir }}"
  loop_control:
    index_var: idx
  when: inventory_hostname == 'dat_local'

- name: DAT | ASSETS - PUSH | push assets from controller to remote
  synchronize:
    src: "{{ dat_assets_controller_temp_dir }}/{{ idx }}/"
    dest: "{{ item.remote }}"
    mode: push
    archive: no
    delete: "{{ dat_assets_remote_delete }}"
    recursive: yes
    checksum: yes
  with_items: "{{ dat_assets_dir }}"
  loop_control:
    index_var: idx
  when: inventory_hostname == 'dat_remote'

- name: DAT | ASSETS - PUSH | clean assets from the controller (post-work)
  include_tasks: assets_clean.yml
