---
- name: DAT | ASSETS - PULL | clean assets from the controller (pre-work)
  include_tasks: assets_clean.yml

- name: DAT | ASSETS - PULL | pull assets from remote to controller
  synchronize:
    src: "{{ item.remote }}"
    dest: "{{ dat_assets_controller_temp_dir }}/{{ idx }}"
    mode: pull
    archive: no
    delete: yes
    recursive: yes
  with_items: "{{ dat_assets_dir }}"
  loop_control:
    index_var: idx
  when: inventory_hostname == 'dat_remote'

- name: DAT | ASSETS - PULL | push assets from controller to local
  synchronize:
    src: "{{ dat_assets_controller_temp_dir }}/{{ idx }}/"
    dest: "{{ item.local }}"
    mode: push
    archive: no
    delete: "{{ dat_assets_local_delete }}"
    recursive: yes
  with_items: "{{ dat_assets_dir }}"
  loop_control:
    index_var: idx
  when: inventory_hostname == 'dat_local'

- name: DAT | ASSETS - PULL | clean assets from the controller (post-work)
  include_tasks: assets_clean.yml
