---
- name: DAT | DB - PULL | Create remote db dump
  mysql_db:
    name: "{{ dat_db_name }}"
    target: "{{ dat_db_remote_temp_file }}"
    state: dump
  when: inventory_hostname == 'dat_remote'

- name: DAT | DB - PULL | Copy remote db dump to controller
  synchronize:
    src: "{{ dat_db_remote_temp_file }}"
    dest: "{{ dat_db_controller_temp_file }}"
    mode: pull
  when: inventory_hostname == 'dat_remote'

- name: DAT | DB - PULL | Cleanup remote db dump
  file:
    path: "{{ dat_db_remote_temp_file }}"
    state: absent
  when: inventory_hostname == 'dat_remote' and dat_db_remote_clean

- name: DAT | DB - PULL | Copy controller db dump to local
  synchronize:
    src: "{{ dat_db_controller_temp_file }}"
    dest: "{{ dat_db_local_temp_file }}"
    mode: push
  when: inventory_hostname == 'dat_local'

- name: DAT | DB - PULL | Import db dump to local
  mysql_db:
    name: "{{ dat_db_name }}"
    target: "{{ dat_db_local_temp_file }}"
    state: import
  when: inventory_hostname == 'dat_local'

- name: DAT | DB - PULL | Cleanup local db dump
  file:
    path: "{{ dat_db_local_temp_file }}"
    state: absent
  when: inventory_hostname == 'dat_local' and dat_db_local_clean
